config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "tweets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tweet.rb
class Tweet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]

  # GET /tweets or /tweets.json
  def index
    # Tweet.new para que aparezca el form new en index
    @tweet = Tweet.new
    @tweets = Tweet.all
    # Agrego a pagy  le indico que muestre del más reciente al más antiguo
    @pagy, @tweets = pagy(Tweet.all.order(:created_at => :desc))
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
         # format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully created." }
        # Redirecciono a la vista index en vez de ir a la vista new
        format.html { redirect_to tweets_url, notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:user_name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    # Helper de pagy
    include Pagy::Frontend
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClonTwitter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="home">
    <%= render "shared/columna_izquierda" %>

    <div class="centrado">
      <div class="columna centro">
        <%= yield %>
      </div>
    </div>

    <%= render "shared/columna_derecha" %>

  </body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</html>

app/views/shared/_columna_derecha.html.erb
<div class="columna der">

        <div class="der__search">
          <input class="der__input" type="text" placeholder="Buscar en Twitter">
        </div>

        <div class="der__pasando">
            <h2 class="pasando__h2">Qué está pasando</h2>
            <ul class="pasando__ul">
                    <li class="pasando__li">
                        <a class="pasando__a" href="#" title="Random">
                            <span class="pasando__claim">Actualidad · Hace 5 horas</span>
                            <h3>Lanzan ropa interior autolimpiante, que se puede usar durante semanas sin que apeste.</h3>
                        </a>
                    </li>
                    <li class="pasando__li">
                        <a class="pasando__a" href="#" title="Random">
                            <span class="pasando__claim">ECONOMÍA · Hace 5 horas</span>
                            <h3>La máquina expendedora que vende lingotes de oro.</h3>
                        </a>
                    </li>
                    <li class="pasando__li">
                            <a class="pasando__a" href="#" title="Random">
                                <div class="user">
                                    <img class="user__img" src="https://thispersondoesnotexist.com/" alt="Foto">

                                    <h4 class="user__p">ElonMusk</h4>
                                    <span class="pasando__claim"> Hace 4 horas</span>
                                </div>
                                <h3>Inventan motocicleta que usa cerveza como combustible.</h3>
                            </a>
                        </li>
                    <li class="pasando__li">
                        <a class="pasando__a" href="#" title="Random">
                            <span class="pasando__claim">COVID-19 · Hace 4 horas</span>
                            <h3>Científicos de la Universidad de Oxford</h3>
                            <div class="pasando__tendencias">
                                Tendencias <span>Palabra</span>
                            </div>
                        </a>
                    </li>

                    <li class="pasando__li">
                        <a class="pasando__a" href="#" title="Random">
                            <span class="pasando__claim">NOTICIA · Hace 4 horas</span>
                            <h3>Subway regalará sandwiches de por vida a quien se cambie su nombre a Subway</h3>
                            <div class="pasando__tendencias">
                                Tendencias <span>Palabra</span>
                            </div>
                        </a>
                    </li>
                </ul>
                <a class="der__mostrar" href="#" title="Mostrar Más">Mostrar Más</a>
        </div>

        <div class="der__seguir">
            <h2 class="seguir__h2">A quién seguir</h2>
            <ul class="seguir__ul">
                <li class="seguir__li">
                    <img class="seguir__user" src="https://thispersondoesnotexist.com/" alt="Fake_photo">
                    <div class="seguir__text">
                      <h4 class="seguir__h4">Mark Zuckerberg</h4>
                      <p class="seguir__p">@zucky</p>
                    </div>
                    <a class="seguir__a" href="#" title="Seguir">Seguir</a>
                </li>
                <li class="seguir__li">
                    <img class="seguir__user" src="https://thispersondoesnotexist.com/" alt="Fake_photo">
                    <div class="seguir__text">
                      <h4 class="seguir__h4">Elon Musk</h4>
                      <p class="seguir__p">@x_man</p>
                    </div>
                    <a class="seguir__a" href="#" title="Seguir">Seguir</a>
                </li>
                <li class="seguir__li">
                    <img class="seguir__user" src="https://thispersondoesnotexist.com/" alt="Fake_photo">
                    <div class="seguir__text">
                      <h4 class="seguir__h4">Steve Jobs</h4>
                      <p class="seguir__p">@apple1</p>
                    </div>
                    <a class="seguir__a" href="#" title="Seguir">Seguir</a>
                </li>
                <a class="der__mostrar" href="#" title="Mostrar Más">Mostrar Más</a>
            </ul>
        </div>

        <ul class="der__ul">
            <li class="der__li"><a href="#" title="Acerca de">Acerca de</a></li>
            <li class="der__li"><a href="#" title="Centro de ayuda">Centro de ayuda</a></li>
            <li class="der__li"><a href="#" title="Condiciones de Servicio">Condiciones de Servicio</a></li>
            <li class="der__li"><a href="#" title="Política de Privacidad">Política de Privacidad</a></li>
            <li class="der__li"><a href="#" title="Política de cookies">Política de cookies</a></li>
            <li class="der__li"><a href="#" title="Información de anuncios">Información de anuncios</a></li>
            <li class="der__li">© 2023 Twitter, Inc.</li>
        </ul>
    </div>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <% if tweet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_name, style: "display: block" %>
    <%= form.text_field :user_name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<div id="<%= dom_id tweet %>">
  <p>
    <strong>User name:</strong>
    <%= tweet.user_name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= tweet.description %>
  </p>

</div>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Show this tweet", @tweet %> |
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/index.html.erb
<p style="color: green"><%= notice %></p>

<!-- <h1>Twitter</>-->

<!-- <%= link_to "New tweet", new_tweet_path, class:'btn btn-primary', type:'button' %> -->

      <div class="columna centro">
        <div class="centro__titular">
          <h2 class="centro__h2">Inicio</h2>
          <svg class="centro__svg" viewBox="0 0 24 24"><g><path d="M22.772 10.506l-5.618-2.192-2.16-6.5c-.102-.307-.39-.514-.712-.514s-.61.207-.712.513l-2.16 6.5-5.62 2.192c-.287.112-.477.39-.477.7s.19.585.478.698l5.62 2.192 2.16 6.5c.102.306.39.513.712.513s.61-.207.712-.513l2.16-6.5 5.62-2.192c.287-.112.477-.39.477-.7s-.19-.585-.478-.697zm-6.49 2.32c-.208.08-.37.25-.44.46l-1.56 4.695-1.56-4.693c-.07-.21-.23-.38-.438-.462l-4.155-1.62 4.154-1.622c.208-.08.37-.25.44-.462l1.56-4.693 1.56 4.694c.07.212.23.382.438.463l4.155 1.62-4.155 1.622zM6.663 3.812h-1.88V2.05c0-.414-.337-.75-.75-.75s-.75.336-.75.75v1.762H1.5c-.414 0-.75.336-.75.75s.336.75.75.75h1.782v1.762c0 .414.336.75.75.75s.75-.336.75-.75V5.312h1.88c.415 0 .75-.336.75-.75s-.335-.75-.75-.75zm2.535 15.622h-1.1v-1.016c0-.414-.335-.75-.75-.75s-.75.336-.75.75v1.016H5.57c-.414 0-.75.336-.75.75s.336.75.75.75H6.6v1.016c0 .414.335.75.75.75s.75-.336.75-.75v-1.016h1.098c.414 0 .75-.336.75-.75s-.336-.75-.75-.75z"></path></g></svg>
        </div>
        <div class="centro__pasando">
          <div class="pasando__up ">
            <img class="pasando__img" id="rostro-ficticio" src="https://thispersondoesnotexist.com/?123" alt="Rostro Ficticio">
            <!-- <textarea class="pasando__textarea" placeholder="¿Qué está pasando?"></textarea>-->
            <!-- Agrego el formulario new en index para simular la creación del tweet -->
              <div class="pasando__textarea">
                <%= form_with(model: @tweet, local: true) do |form| %>
                  <div class="mb-3">
                    <!-- Ingreso texto user -->
                    <%= form.label :user_name, class: "form-label" %>
                    <%= form.text_field :user_name, class: "form-control" %>
                    <!-- Ingreso texto description -->
                    <%= form.label :description, class: "form-label" %>
                    <%= form.text_area :description, class: "form-control" %>
                  </div>
                  <%= form.submit "Tweet", class: "btn btn-primary" %>
                <% end %>
              </div>
          </div>
          <div class="pasando__inf">
            <ul class="pasando__ul">
              <li class="pasando__li">
                <svg class="pasando__icon" viewBox="0 0 24 24"><g><path d="M3 5.5C3 4.119 4.119 3 5.5 3h13C19.881 3 21 4.119 21 5.5v13c0 1.381-1.119 2.5-2.5 2.5h-13C4.119 21 3 19.881 3 18.5v-13zM5.5 5c-.276 0-.5.224-.5.5v9.086l3-3 3 3 5-5 3 3V5.5c0-.276-.224-.5-.5-.5h-13zM19 15.414l-3-3-5 5-3-3-3 3V18.5c0 .276.224.5.5.5h13c.276 0 .5-.224.5-.5v-3.086zM9.75 7C8.784 7 8 7.784 8 8.75s.784 1.75 1.75 1.75 1.75-.784 1.75-1.75S10.716 7 9.75 7z"></path><circle cx="8.868" cy="8.309" r="1.542"></circle></g></svg>
              </li>
              <li class="pasando__li">
                <svg class="pasando__icon" viewBox="0 0 24 24"><g><path d="M3 5.5C3 4.119 4.12 3 5.5 3h13C19.88 3 21 4.119 21 5.5v13c0 1.381-1.12 2.5-2.5 2.5h-13C4.12 21 3 19.881 3 18.5v-13zM5.5 5c-.28 0-.5.224-.5.5v13c0 .276.22.5.5.5h13c.28 0 .5-.224.5-.5v-13c0-.276-.22-.5-.5-.5h-13zM18 10.711V9.25h-3.74v5.5h1.44v-1.719h1.7V11.57h-1.7v-.859H18zM11.79 9.25h1.44v5.5h-1.44v-5.5zm-3.07 1.375c.34 0 .77.172 1.02.43l1.03-.86c-.51-.601-1.28-.945-2.05-.945C7.19 9.25 6 10.453 6 12s1.19 2.75 2.72 2.75c.85 0 1.54-.344 2.05-.945v-2.149H8.38v1.032H9.4v.515c-.17.086-.42.172-.68.172-.76 0-1.36-.602-1.36-1.375 0-.688.6-1.375 1.36-1.375z"></path></g></svg>
              </li>
              <li class="pasando__li">
                <svg class="pasando__icon" viewBox="0 0 24 24"><g><path d="M6 5c-1.1 0-2 .895-2 2s.9 2 2 2 2-.895 2-2-.9-2-2-2zM2 7c0-2.209 1.79-4 4-4s4 1.791 4 4-1.79 4-4 4-4-1.791-4-4zm20 1H12V6h10v2zM6 15c-1.1 0-2 .895-2 2s.9 2 2 2 2-.895 2-2-.9-2-2-2zm-4 2c0-2.209 1.79-4 4-4s4 1.791 4 4-1.79 4-4 4-4-1.791-4-4zm20 1H12v-2h10v2zM7 7c0 .552-.45 1-1 1s-1-.448-1-1 .45-1 1-1 1 .448 1 1z"></path></g></svg>
              </li>
              <li class="pasando__li">
                <svg class="pasando__icon" viewBox="0 0 24 24"><g><path d="M6 3V2h2v1h6V2h2v1h1.5C18.88 3 20 4.119 20 5.5v2h-2v-2c0-.276-.22-.5-.5-.5H16v1h-2V5H8v1H6V5H4.5c-.28 0-.5.224-.5.5v12c0 .276.22.5.5.5h3v2h-3C3.12 20 2 18.881 2 17.5v-12C2 4.119 3.12 3 4.5 3H6zm9.5 8c-2.49 0-4.5 2.015-4.5 4.5s2.01 4.5 4.5 4.5 4.5-2.015 4.5-4.5-2.01-4.5-4.5-4.5zM9 15.5C9 11.91 11.91 9 15.5 9s6.5 2.91 6.5 6.5-2.91 6.5-6.5 6.5S9 19.09 9 15.5zm5.5-2.5h2v2.086l1.71 1.707-1.42 1.414-2.29-2.293V13z"></path><circle cx="14.738" cy="9.458" r="1.478"></circle><circle cx="9.262" cy="9.458" r="1.478"></circle></g></svg>
              </li>
              <li class="pasando__li">
                <svg class="pasando__icon" viewBox="0 0 24 24"><g><path d="M-37.9 18c-.1-.1-.1-.1-.1-.2.1 0 .1.1.1.2z"></path><path d="M-37.9 18c-.1-.1-.1-.1-.1-.2.1 0 .1.1.1.2zM18 2.2h-1.3v-.3c0-.4-.3-.8-.8-.8-.4 0-.8.3-.8.8v.3H7.7v-.3c0-.4-.3-.8-.8-.8-.4 0-.8.3-.8.8v.3H4.8c-1.4 0-2.5 1.1-2.5 2.5v13.1c0 1.4 1.1 2.5 2.5 2.5h2.9c.4 0 .8-.3.8-.8 0-.4-.3-.8-.8-.8H4.8c-.6 0-1-.5-1-1V7.9c0-.3.4-.7 1-.7H18c.6 0 1 .4 1 .7v1.8c0 .4.3.8.8.8.4 0 .8-.3.8-.8v-5c-.1-1.4-1.2-2.5-2.6-2.5zm1 3.7c-.3-.1-.7-.2-1-.2H4.8c-.4 0-.7.1-1 .2V4.7c0-.6.5-1 1-1h1.3v.5c0 .4.3.8.8.8.4 0 .8-.3.8-.8v-.5h7.5v.5c0 .4.3.8.8.8.4 0 .8-.3.8-.8v-.5H18c.6 0 1 .5 1 1v1.2z"></path><path d="M15.5 10.4c-3.4 0-6.2 2.8-6.2 6.2 0 3.4 2.8 6.2 6.2 6.2 3.4 0 6.2-2.8 6.2-6.2 0-3.4-2.8-6.2-6.2-6.2zm0 11c-2.6 0-4.7-2.1-4.7-4.7s2.1-4.7 4.7-4.7 4.7 2.1 4.7 4.7c0 2.5-2.1 4.7-4.7 4.7z"></path><path d="M18.9 18.7c-.1.2-.4.4-.6.4-.1 0-.3 0-.4-.1l-3.1-2v-3c0-.4.3-.8.8-.8.4 0 .8.3.8.8v2.2l2.4 1.5c.2.2.3.6.1 1z"></path></g></svg>
              </li>
            </ul>

          </div>
        </div>
      </div>
      <!--FIN BLOQUE INGRESE TWEET-->
<div id="tweets">
  <!--Muestro los tweets de la base de datos dentro del formato de los tweets-->
  <% @tweets.each do |tweet| %>
  <div class="centro__tweets">
          <section class="centro__tweet">
              <div class="centro__col">
                  <img class="centro__user" src="https://thispersondoesnotexist.com/" alt="User">
              </div>
              <div class="centro__col">
                <div class="centro__row centro__row--user">
                  <h3 class="centro__h3">  <%= tweet.user_name %>  </h3>
                  <h4 class="centro__h4">@<%= tweet.user_name %></h4>
                  <span class="centro__tiempo">15s</span>
                </div>
                <div class="centro__row">
                  <p class="centro__text"><%= tweet.description %><%= link_to "Show this tweet", tweet %></p>
                  <!-- Carga imagen aleatoria asignándole un id al azar para que cada imagen de los tweets sea diferente-->
                  <% random_id = rand(1..999) %>
                  <img class="centro__img" src="https://picsum.photos/id/<%= random_id %>/420/240" alt="">
                </div>
                <ul class="centro__ul">
                  <li class="centro__li">
                      <svg class="centro__svg" viewBox="0 0 24 24"><g><path d="M14.046 2.242l-4.148-.01h-.002c-4.374 0-7.8 3.427-7.8 7.802 0 4.098 3.186 7.206 7.465 7.37v3.828c0 .108.044.286.12.403.142.225.384.347.632.347.138 0 .277-.038.402-.118.264-.168 6.473-4.14 8.088-5.506 1.902-1.61 3.04-3.97 3.043-6.312v-.017c-.006-4.367-3.43-7.787-7.8-7.788zm3.787 12.972c-1.134.96-4.862 3.405-6.772 4.643V16.67c0-.414-.335-.75-.75-.75h-.396c-3.66 0-6.318-2.476-6.318-5.886 0-3.534 2.768-6.302 6.3-6.302l4.147.01h.002c3.532 0 6.3 2.766 6.302 6.296-.003 1.91-.942 3.844-2.514 5.176z"></path></g></svg>
                      <span class="centro__numero">1</span>
                  </li>
                  <li class="centro__li">
                      <svg class="centro__svg" viewBox="0 0 24 24"><g><path d="M23.77 15.67c-.292-.293-.767-.293-1.06 0l-2.22 2.22V7.65c0-2.068-1.683-3.75-3.75-3.75h-5.85c-.414 0-.75.336-.75.75s.336.75.75.75h5.85c1.24 0 2.25 1.01 2.25 2.25v10.24l-2.22-2.22c-.293-.293-.768-.293-1.06 0s-.294.768 0 1.06l3.5 3.5c.145.147.337.22.53.22s.383-.072.53-.22l3.5-3.5c.294-.292.294-.767 0-1.06zm-10.66 3.28H7.26c-1.24 0-2.25-1.01-2.25-2.25V6.46l2.22 2.22c.148.147.34.22.532.22s.384-.073.53-.22c.293-.293.293-.768 0-1.06l-3.5-3.5c-.293-.294-.768-.294-1.06 0l-3.5 3.5c-.294.292-.294.767 0 1.06s.767.293 1.06 0l2.22-2.22V16.7c0 2.068 1.683 3.75 3.75 3.75h5.85c.414 0 .75-.336.75-.75s-.337-.75-.75-.75z"></path></g></svg>
                      <span class="centro__numero">1</span>
                  </li>
                  <li class="centro__li">
                      <svg class="centro__svg" viewBox="0 0 24 24"><g><path d="M12 21.638h-.014C9.403 21.59 1.95 14.856 1.95 8.478c0-3.064 2.525-5.754 5.403-5.754 2.29 0 3.83 1.58 4.646 2.73.814-1.148 2.354-2.73 4.645-2.73 2.88 0 5.404 2.69 5.404 5.755 0 6.376-7.454 13.11-10.037 13.157H12zM7.354 4.225c-2.08 0-3.903 1.988-3.903 4.255 0 5.74 7.034 11.596 8.55 11.658 1.518-.062 8.55-5.917 8.55-11.658 0-2.267-1.823-4.255-3.903-4.255-2.528 0-3.94 2.936-3.952 2.965-.23.562-1.156.562-1.387 0-.014-.03-1.425-2.965-3.954-2.965z"></path></g></svg>
                    <span class="centro__numero">1</span>
                  </li>
                  <li class="centro__li">
                      <svg class="centro__svg" viewBox="0 0 24 24"><g><path d="M17.53 7.47l-5-5c-.293-.293-.768-.293-1.06 0l-5 5c-.294.293-.294.768 0 1.06s.767.294 1.06 0l3.72-3.72V15c0 .414.336.75.75.75s.75-.336.75-.75V4.81l3.72 3.72c.146.147.338.22.53.22s.384-.072.53-.22c.293-.293.293-.767 0-1.06z"></path><path d="M19.708 21.944H4.292C3.028 21.944 2 20.916 2 19.652V14c0-.414.336-.75.75-.75s.75.336.75.75v5.652c0 .437.355.792.792.792h15.416c.437 0 .792-.355.792-.792V14c0-.414.336-.75.75-.75s.75.336.75.75v5.652c0 1.264-1.028 2.292-2.292 2.292z"></path></g></svg>
                  </li>
                </ul>
              </div>
          </section>

        </div>


    <hr>
    <p>
      <!-- <%= link_to "Show this tweet", tweet %> -->
    </p>
  <% end %>
</div>


<%== pagy_bootstrap_nav(@pagy) %>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tweet %>

<div>
  <%= link_to "Edit this tweet", edit_tweet_path(@tweet) %> |
  <%= link_to "Back to tweets", tweets_path %>

  <%= button_to "Destroy this tweet", @tweet, method: :delete %>
</div>